### PR TITLE
Create dislocatedAnatomicalEntityInLocation.yaml

### PR DESCRIPTION
**Pull request by nicolevasilevsky**

### CODE REVIEW

**Comment by matentzn** [comment]
Thanks @nicolevasilevsky How does this differ from:
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormalPositionOfAnatomicalEntityInLocation.yaml

**Comment by nicolevasilevsky** [comment]
I missed that! We can use that pattern and delete my new pattern.

Thanks @matentzn

**Comment by matentzn** [comment]
Will you make a ticket for changing dislocated Anatomical entity to abnormalPositionOf? This should probably be documented the uPheno tracker as well, so that others like MP can do the same.

**Comment by nicolevasilevsky** [comment]
@matentzn I'm not sure what you mean, could you clarify?

dislocated anatomical entity would be included in the abnormal position of pattern, because dislocated is a subclass of position.

What do you want a ticket to say?

**Comment by matentzn** [comment]
I mean, if anyone is using dislocated, should they not be switching to the position pattern? Why use dislocated at all? -> remember all EQs should have a pattern! Even if dislocated is a sub of position, it wont fit into the pattern (which is only position, not its subs).

**Pull request closed without merging**
