### PR TITLE
Refreshed GO import - fixes #256

### LINKED ISSUE #256: Invalid use of "part of" characteristics make reasoning behaviour unspecified.
The Human phenotype ontology, as currently located at http://purl.obolibrary.org/obo/hp.owl, is dependent on a upheno import (http://purl.obolibrary.org/obo/upheno/imports/go_import.owl) which is not in OWL 2 DL. As far as I can see, the reason for that is a violation of a global constraint, (irregular role hierarchy):

`Use of non-simple property in functional axiom <http://purl.obolibrary.org/obo/BFO_0000050> [FunctionalObjectProperty(<http://purl.obolibrary.org/obo/BFO_0000050>) in OntologyID(OntologyIRI(<http://purl.obolibrary.org/obo/upheno/imports/go_import.owl>) VersionIRI(<null>))]
`

On closer look, it seems that 'part of' (the relation causing the problem), is specified as both transitive and functional. Taking a look at RO, 'part of' is merely transitive. I think this should be fixed asap, as complete reasoning is otherwise not possible (in fact, HermiT refuses to even try classifying HP).

### PR DESCRIPTION
**Pull request by balhoff**
Tested with released MP and HP; shouldn't cause incoherency. Fixes #256.

### CODE REVIEW

**Comment by balhoff** [comment]
Hmm, thanks for catching that. I just used the Makefile target. I wonder how the old one was made?

**Comment by matentzn** [comment]
@cmungall @dosumis Do you happen to know?

**Comment by drseb** [comment]
The last version was generated by me, right? https://github.com/obophenotype/upheno/blob/master/imports/go_import.owl

Well. I just use `make imports/go_import.owl`, but I guess it depends on which version of owltools you use.

**Comment by balhoff** [comment]
I looked at an earlier version, and it is just a hierarchy. I'm going to merge this for now, since this is what the Makefile produces, and the current version is invalid OWL due to the now-fixed GO part_of problem.

**Pull request merged**
