### PR TITLE
DO NOT MERGE: Modelling cellular motility

### PR DESCRIPTION
**Pull request by matentzn**
Hey @ybradford @chris-grove @seger @dosumis can you please tell me if this makes sense?

My problem is to understand what the correct bearer is in this case. To deal with [this](https://github.com/obophenotype/xenopus-phenotype-ontology/issues/58), what exactly is the thing that has impaired motility: the cilium or the whole cell (due to some effect on the cilium).

I preferred here to use the GO modelling pattern rather than the PATO one, because the PATO terms for increased cellular motility seem to be [marked for obsoletion](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001488). Thanks for feedback.

### CODE REVIEW

**Comment by dosumis** [comment]
> what exactly is the thing that has impaired motility: the cilium or the whole cel

Cillium

**Comment by matentzn** [comment]
Perfect, then this pattern is correct I assume?

**Comment by dosumis** [comment]
> Perfect, then this pattern is correct I assume?

Nope.  

```yaml
text: >
   'has_part' some ('process quality' and 
       ('inheres_in' some (%s and ('occurs_in' some 'cell motility')))
        and ('has_modifier' some 'abnormal'))
vars:
   - cellular_component
```

1. process and 'cellular component' are in the wrong places (process occurs in CC, not CC occurs in P)
3. The Process '[cell motility](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0048870&viewMode=All&siblings=false)' refers to cells moving.  This is a cell part moving, which is sometimes, but not  necessarily involved in cells moving.  Many  of the cells in the  spreadsheet attached to  https://github.com/obophenotype/xenopus-phenotype-ontology/issues/58 are not motile. 

GO:[movement of cell or subcellular component](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0006928&viewMode=All&siblings=false) would work for a  general pattern:

```yaml
text: >
   'has_part' some ('process quality' and 
       ('inheres_in' some ('movement of cell or subcellular component'
            and ('occurs_in' some %s)))
        and ('has_modifier' some 'abnormal'))
vars:
   - cellular_component
```

Note: GO actually has a term for ['cilium movement' ](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0003341).  

It looks like the GO term  has no formal definition. We should make a GO ticket to request that it be defined as EquivalentTo: 'movement of cell or subcellular component' that occurs in some 'cillium'
=> equivalence between pattern generated phenotype def and the same using the named term.

BTW: It is very important to get patterns right for cilia phenotypes - there are important to a lot of genetic diseases (see ciliopathy; Ciliary dyskinesia).

**Comment by matentzn** [comment]
Thank you David, that was sloppy on my part..

Ok from what you are saying, I prefer to actually go the GO route on this one and use the "abnormal Biological Process" pattern then.

However, this whole issue reveals one slight modelling vagueness I wanted always clarified.

Lets look at the following to sentences:

(a) abnormal movement of cilium
(b) abnormal cell proliferation in liver

in (b), it is pretty clear that the cell proliferation occurs within a location, hence the "abnormalBiologicalProcessInLocation" pattern and the use of occurs_in.

In (a) again, the `bearer` is, a biological process: `movement of cilium`. Should this process:

(i) `occurs in` cilium (indicating that the cilium is the location in which the process occurs)
(ii) `has affected component` (or some such) cilium
(iii) `occurs in` cell and `has affected component` (or some such) cilium

If (ii) or (iii), what is the correct RO relation?

**Comment by dosumis** [comment]
Good point:

> (i) occurs in cilium (indicating that the cilium is the location in which the process occurs)
> (ii) has affected component (or some such) cilium
> (iii) occurs in cell and has affected component (or some such) cilium

> If (ii) or (iii), what is the correct RO relation?

I  agree - occurs_in is not the right relation here.   The  cilium is a (the?) active participant in process of movement.   I suggest
[has_active_participant](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002218).  This needs to be co-ordinated with GO - there post-composition needs to follow the same pattern as ours.

There's some danger that other  participants might be considered active here so this might not be completely safe (necessary and sufficient), but I think it's good enough to go with.

BTW  - I think varient (iii) is unecessary and may even be  wrong in this case (the cilia stick out of the cell so we could say they  move in extracellular space.

**Comment by dosumis** [comment]
Suggested pattern:

```yaml
text: >
   'has_part' some ('process quality' and 
       ('inheres_in' some ('movement of cell or subcellular component'
            and ('has active participant' some %s)))
        and ('has_modifier' some 'abnormal'))
vars:
   - cellular_component
```

**Comment by matentzn** [comment]
So this is the slightly generalised version of your suggested pattern:

```
pattern_name: abnormalBiologicalProcessWithActiveParticipant
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalBiologicalProcessWithActiveParticipant.yaml
description: "An abnormal biological process involving an active participant. Examples include 'Abnormal cilium motility' (a combination of 'GO:cell motility' and the active participant 'cilium')."

contributors:
  - https://orcid.org/0000-0002-7356-1779

classes:
  process quality: PATO:0001236
  abnormal: PATO:0000460
  biological process: GO:0008150
  participant: BFO:0000004

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051
  has_active_participant: RO:0002218

vars:
 biological_process: "'cellular component'"
 participant: "'participant'"
 
name:
  text: "abnormal %s involving %s"
  vars:
   - biological_process
   - participant

def:
  text: "Abnormal %s involving the active participant %s."
  vars:
    - biological_process
    - participant

equivalentTo:
  text: "'has_part' some ('process quality' and ('inheres_in' some (%s and ('has_active_participant' some %s))) and ('has_modifier' some 'abnormal'))"
  vars:
    - biological_process
    - participant
```

**Comment by dosumis** [comment]
Prefer the specific one.  I think the general pattern will sound a bit odd and abstracted to most users.  

`abnormalBiologicalProcessWithActiveParticipant`

Most or all processes we're interested in have active participants (AKA agents).  What we mean is an abonormal process defined by it's active participant.  Also, we're asking users to cope with two abstractions here (BP & Active Participant).  This might be more readily understandable: `abnormalCellularComponentProcess`

**Comment by matentzn** [comment]
Pattern 1 in the PR:

abnormalMotilityOfCellularComponent:

```
pattern_name: abnormalMotilityOfCellularComponent
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalMotilityOfCellularComponent.yaml
description: "An abnormality of the ability to move (motility) a cellular component/cells. Examples include 'Abnormal cilium motility'."

contributors:
  - https://orcid.org/0000-0002-7356-1779

classes:
  process quality: PATO:0001236
  abnormal: PATO:0000460
  cellular component: GO:0005575
  movement of cell or subcellular component: GO:0006928

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051
  results_in_movement_of: RO:0002565

vars:
 cellular_component: "'cellular component'"
 
name:
  text: "abnormal %s motility"
  vars:
   - cellular_component

def:
  text: "Abnormal ability to move %s."
  vars:
    - cellular_component

equivalentTo:
  text: "'has_part' some ('process quality' and ('inheres_in' some ('movement of cell or subcellular component' and ('results_in_movement_of' some %s))) and ('has_modifier' some 'abnormal'))"
  vars:
    - cellular_component
```

**Comment by matentzn** [comment]
Pattern 2:

```
pattern_name: abnormalCellularComponentProcess
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalCellularComponentProcess.yaml
description: "An abnormal biological process involving the participation of a cellular component."

contributors:
  - https://orcid.org/0000-0002-7356-1779

classes:
  process quality: PATO:0001236
  abnormal: PATO:0000460
  biological process: GO:0008150
  cellular component: GO:0005575

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051
  has_participant: RO:0002218

vars:
 cellular_component: "'cellular component'"
 biological_process: "'biological process'"
 
name:
  text: "abnormal %s involving %s"
  vars:
   - biological_process
   - cellular_component

def:
  text: "Abnormal %s involving the active participant %s."
  vars:
    - biological_process
    - cellular_component

equivalentTo:
  text: "'has_part' some ('process quality' and ('inheres_in' some (%s and ('has_participant' some %s))) and ('has_modifier' some 'abnormal'))"
  vars:
    - biological_process
    - cellular_component

```

**Comment by matentzn** [comment]
I assume its fine for now; we will discuss tomorrow in the call

**Pull request merged**
