### PR TITLE
Create abnormalFractureOfAnatomicalEntity.yaml

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
https://github.com/obophenotype/human-phenotype-ontology/issues/3889
@callahantiff and I are working on the ticket above - @pnrobinson suggested that we make a pattern for bone fractures as a starting place for all the terms she wants to add to HPO.

Let us know if this looks okay.

### CODE REVIEW

**Comment by matentzn** [comment]
Are these fractures really abnormal or rather pathological (@dosumis )

**Comment by nicolevasilevsky** [comment]
Good question. There are other fracture terms in HPO that use this pattern such as:
'Fractured hand bones'
'Fractured forearm bones'
'Fractures of the long bones'

**Comment by dosumis** [comment]
Presumably there's no such thing as a normal fracture, but all fractures are pathological.  @pnrobinson ?

**Comment by pnrobinson** [comment]
A normal fracture is when you fall off your bike and break your arm. 
A pathological fracture means that for instance you have cancer and a metastasis has weakened a bone that then fractures without an adequate trauma.

**Comment by matentzn** [comment]
@nicolevasilevsky Can you add some more detailed description along the lines what Peter suggested and then merge the pattern?

**Comment by nicolevasilevsky** [comment]
> Can you add some more detailed description along the lines what Peter suggested and then merge the pattern?

I added the description:
"An abnormal fracture in an anatomical entity. A normal fracture is when you fall off your bike and break your arm. A pathological or abnormal fracture means that for instance you have cancer and a metastasis has weakened a bone that then fractures without an adequate trauma."

I will merge this

**Pull request merged**
