### PR TITLE
WIP: Create abnormallyNectroticdAnatomicalEntities.yaml

### PR DESCRIPTION
**Pull request by nicolevasilevsky**

### CODE REVIEW

**Comment by matentzn** [comment]
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/necroticAnatomicalEntity.yaml

Can you double check why this pattern wouldn’t work? :P sorry. We just created it last week!

**Comment by nicolevasilevsky** [comment]
Oh, I didn't realize that was there! It doesn't look like we have the PATO necrotic term in HP, I will add it

**Comment by nicolevasilevsky** [comment]
I don't see any reason this wouldn't work. I just tested it on one term and it seemed fine.

Should we go with this necrosis pattern instead?

**Comment by matentzn** [comment]
If the intention is the same, we should always use the same pattern!

**Comment by matentzn** [comment]
If you prefer the one you have here, open a ticket about the necrosis pattern and ask @sbello which one she likes more; no matter what, there should only be one.

**Comment by matentzn** [comment]
(Btw there is a typo in the pattern iri)

**Comment by nicolevasilevsky** [comment]
I prefer this pattern:
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/necroticAnatomicalEntity.yaml

I hope we can use this one in HPO and get rid of this one that I just created

**Comment by matentzn** [comment]
@nicolevasilevsky will you be responsible for championing this change?

**Comment by nicolevasilevsky** [comment]
Yes, I will update the logical defs for necrosis terms in HP

**Pull request closed without merging**
