### PR TITLE
Abnormal pigmentation

### PR DESCRIPTION
**Pull request by srobb1**
This is 3 patterns: 
  - abnormalPigmentation
  - increasedPigmentation
  - decreasedPigmentation

I have the entity limited to 'Anatomical Entity', but this could be further restricted to 'organ: UBERON:0000062

This pattern is used in PLANP to describe phenotypes that result in changes in pigmentation

examples:
  - 'decreased pigmentation' of the eye
  - 'decreased pigmentation' of the 'definitive epidermis'

### CODE REVIEW

**Comment by srobb1** [comment]
I also added loss of pigmentation to this pull request.

**Comment by sbello** [comment]
Note there is a ticket https://github.com/obophenotype/upheno/issues/298 discussing pigmentation patterns

**Comment by srobb1** [comment]
@sbello Thanks! I missed that one. Interesting. I had not been thinking at all about the process which produces pigmentation. Rather just the end result of a visible change in pigmentation.  

These patterns are restricted to anatomical entity and use PATO 'degree of pigmentation', 'unpigmented', 'decreased pigmentation' and 'increased pigmentation' and so they should not cross with a pigmentation process.  But I see that they need be clearly described. 


The pattern mentioned in #298 seems to be about the pigmentation process (decreased rate), right? 
```
'has part' some ('decreased rate'  and ('inheres in' some 
 (pigmentation and ('occurs in' some 'strand of hair')))
   and ('has modifier' some abnormal)
``` 
whereas the ones included here are about change/less/more/no pigment in an anatomical entity, for example:
```
'has_part' some ('decreased pigmentation' and ('inheres_in' some %s) and ('qualifier' some 'abnormal'))
```

I do think it would be great to create a new pattern for alterations of the pigmentation process. This will help to further dissect phenotypes.


here are all my proposed pigmentation patterns:
```
classes:
  entity: UBERON:0001062 

...

text: "has_part' some ('unpigmented' and ('inheres_in' some %s) and ('qualifier' some 'abnormal'))"
  vars:
    - entity
```

```
classes:
  entity: UBERON:0001062 

...
text: "'has_part' some ('decreased pigmentation' and ('inheres_in' some %s) and ('qualifier' some 'abnormal'))"
  vars:
    - entity
```

```
classes:
  entity: UBERON:0001062 

...

text: "'has_part' some ('increased pigmentation' and ('inheres_in' some %s) and ('qualifier' some 'abnormal'))"
  vars:
    - entity
```

```
classes:
  entity: UBERON:0001062 

...

 text: "'has_part' some ('degree of pigmentation' and ('inheres_in' some %s) and ('qualifier' some 'abnormal'))"
  vars:
    - entity
```

I have been wondering if my patterns should be further restricted to 'organ'. In planarians I can only think of phenotypes that result in pigmentation changes in organs such as the eye and the epidermis.

**Comment by sbello** [comment]
As I recall the original discussion was around the difference between the text definitions which talked about abnormal pigment usually in an organ/tissue and the EQ axioms that used the GO process term. It looks like the new PATO terms got added but then the ticket didn't get updated. 

I would suggest not restricting your patterns but instead add a second set for abnormalPigmentationinLocation. I think these will be more widely used but having the broader pattern is still useful.

**Comment by matentzn** [comment]
(dont worry I am merging only to make discussions easier. We will create a new ticket to formally review the pattern)

**Pull request merged**
