### PR TITLE
Create impairedCoordination.yaml

### LINKED ISSUE #619: need to reconcile coordination pattern
HPO uses a PATO class, MP uses an NBO class.

1. Which do we prefer to use?
2. If we go with the NBO class, is increased/decreased rate the right quality?

**HP_0011443 'Abnormality of coordination'**
'has part' some 
    (coordination
     and ('inheres in' some 'multicellular organism')
     and ('has modifier' some abnormal))

**MP_0001405 'impaired coordination'**
'has part' some 
    ('decreased rate'
     and ('inheres in' some 'motor coordination')
     and ('has modifier' some abnormal))

I drafted a pattern here, I'll revise it accordingly once we are in agreement:
https://github.com/obophenotype/upheno/pull/610

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
closes #619

### CODE REVIEW

**Comment by matentzn** [comment]
Didnt we say wrt coordination that we should use abnormallyDecreasedRateOfBehavior instead and avoid coordination as a separate pattern?

**Comment by nicolevasilevsky** [comment]
On the ticket #619, it says to use process quality

> I agree with @sbello on both accounts: 1) NBO should be favoured over PATO and 2) increased rate sounds wrong -> I also think increased process quality may work a bit better here, despite being comparatively devoid of meaning.

**Comment by nicolevasilevsky** [comment]
I feel like we might have discussed this elsewhere too, but I don't see any notes about this in our meeting notes or Slack, or in any other tickets.

**Comment by nicolevasilevsky** [comment]
closing - we can use the impaired behavior pattern for this (at the moment, we don't have a clear distinction between voluntary and involuntary behavior, so they are all subsumed under behavior).

**Pull request closed without merging**
