### PR TITLE
Add new editors workflow document

### LINKED ISSUE #910: We documented the editors’ workflows for maintaining phenotype patterns and harmonizing
We need to document our harmonisation workflow clearly on our website, this is needed for our RPPR this year. @rays22 can we at least create a stub for this, that describes all workflows in uPheno? We need this for the paper, but we need this in the next 3 days for the RPPR as well.

### PR DESCRIPTION
**Pull request by rays22**
If applied, this commit will fix #910 .

### CODE REVIEW

**Comment by matentzn** [comment]
I think to pass the "documentation" threshold this needs more detail; and also, there need to be some sections on the reconciliation workflows (patternisation (ensure all EQs have a pattern); patternisation implementation review (dosdp match->review-> fix, MP);

**Comment by rays22** [comment]
> I think to pass the "documentation" threshold this needs more detail; and also, there need to be some sections on the reconciliation workflows (patternisation (ensure all EQs have a pattern); patternisation implementation review (dosdp match->review-> fix, MP);

I have added more details and text. I am still working on the reconciliation workflow.

**Comment by rays22** [comment]
There is already a placeholder for the [The Phenotype Reconciliation Effort document.](https://github.com/obophenotype/upheno/blob/master/docs/key-topics/reconciliation_effort.md)

**Review by matentzn — APPROVED** [review]
Thanks! You can merge this and add the link to the deployed website to the RPPR.

**Pull request merged**
