### PR TITLE
Create abnormalMorphologyOfCellularComponent.yaml

### PR DESCRIPTION
**Pull request by nicolevasilevsky**

### CODE REVIEW

**Comment by chris-grove** [comment]
@nicolevasilevsky 
Thanks for creating this pattern. We (worm) will definitely use it.

Given all of the discussion about the generic nature of "morphology" (e.g. to include pigemntation, distribution, texture, etc.) it seems that maybe we shouldn't include "shape" in the description or synonym as that would be too specific.

**Comment by nicolevasilevsky** [comment]
Thanks for the suggestion @chris-grove, I revised the description.

**Comment by chris-grove** [comment]
@nicolevasilevsky 
OK, thanks yet the description still doesn't look quite right:

https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormalMorphologyOfCellularComponent.yaml

"An abnormally in the morphology of a cellular component..."

I think maybe it was intended to be:

"An abnormality in the morphology of a cellular component..."

Could also be:

"An abnormal morphology of a cellular component..."

**Comment by nicolevasilevsky** [comment]
Thank you @chris-grove! i fixed it in PR #517

**Pull request merged**
