### PR TITLE
Create abnormalColorOfAnatomicalEntity.yaml

### PR DESCRIPTION
**Pull request by nicolevasilevsky**

### CODE REVIEW

**Comment by matentzn** [comment]
Thx @nicolevasilevsky ! Naively: How can we distinguish this pattern from abnormal pigmentation of anatomical entity? What does the one mean that the other does not? This answer also needs to go in the description.

**Comment by mellybelly** [comment]
Abnormal pigmentation does not necessarily mean a change in color, nor does a change in color require that the root cause be due to a change in the pigment cells/granules. pigment cells are specialized cell type (I had spent a bit of time defining those in CL many years back) and can contain different colored pigment granules. 

There are also differences in the process of pigmentation (such as pattern of cells or pattern of granules in those cells) as well as the dependent continuant that is the color.

**Comment by matentzn** [comment]
Thats great thanks Melissa. I guess than that biocurators now that and the clarification in the pattern description is not required?

**Comment by mellybelly** [comment]
one quick comment here- feel free to make a new ticket - but this is a good example of having related patterns that we might want to have a "see also" sort of field to point at?

**Comment by matentzn** [comment]
Great idea: made a ticket to improve spec wrt to that:
https://github.com/INCATools/dead_simple_owl_design_patterns/issues/52

**Comment by nicolevasilevsky** [comment]
Thanks @mellybelly!

@matentzn I updated the desc.

**Pull request merged**
